name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Set up environment variables
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: echo "export AUTH_TOKEN=${AUTH_TOKEN}" >> $GITHUB_ENV
      
      - name: Run tests with authentication
        run: npm test
